a=str(input('Enter a string '))
a=a.replace('a','')
a=a.replace('A','')
a=a.replace('e','')
a=a.replace('E','')
a=a.replace('i','')
a=a.replace('I','')
a=a.replace('o','')
a=a.replace('O','')
a=a.replace('u','')
a=a.replace('U','')
print(a)
